# =========================
# SITE METADATA
# =========================

title: Niloy Biswas
description: >
  Portfolio of Niloy Biswas â€“ Software Engineer focused on
  Machine Learning, ML Ops, and Research.
url: "https://niloy077.github.io"
baseurl: ""

# =========================
# BUILD SETTINGS
# =========================

theme: null


# =========================
# MARKDOWN / PROCESSING
# =========================

markdown: kramdown
highlighter: rouge

# =========================
# EXCLUDES
# =========================

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
